title: Project

columns:
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          text:
            label: Project Description
            type: textarea
            size: medium
            help: See our content styleguide
            required: true
            minlength: 5
            maxlength: 500
          year:
            before: Finished
            type: number
            width: 1/2
            min: 2000
          budget:
            label: Budget
            type: number
            before: Total
            after: $
            width: 1/2
          category:
            type: select
            options:
              - Audio
              - Video
              - Art
              - Interactive
              - Live Event
            width: 1/2
          client:
            type: text
            width: 1/2
            icon: user
          link:
            type: url
            width: 1/2
          tags:
            type: tags
          location:
            type: locator

  - width: 1/2
    sections:
      gallery:
        headline: Project gallery
        size: tiny
        info: "{{ file.dimensions }}"
        help: Some help text
        type: files
        min: 1 # required number of files
        max: 100 # files
        layout: cards
        template: gallery-image
        image:
          ratio: 1/1
          cover: false
